# Generated by Django 3.2.12 on 2024-06-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('apellidos', models.CharField(max_length=250)),
                ('nombres', models.CharField(max_length=300)),
                ('correo', models.EmailField(max_length=300)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
